# Generated by Django 2.2.4 on 2021-03-29 11:54

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_auto_20210324_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='przedmiot',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('brak', 'Brak'), ('historia', 'Historia'), ('angielski', 'Angielski'), ('informatyka', 'Informatyka'), ('matematyka', 'Matematyka'), ('polski', 'Polski')], default='brak', max_length=30),
        ),
    ]
