# Generated by Django 2.2.4 on 2021-03-30 21:44

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_auto_20210329_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='przedmiot',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('', 'Brak'), ('historia', 'Historia'), ('angielski', 'Angielski'), ('informatyka', 'Informatyka'), ('matematyka', 'Matematyka'), ('polski', 'Polski')], default='brak', max_length=49),
        ),
    ]
