# Generated by Django 2.2.4 on 2021-03-30 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_auto_20210330_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cena',
            field=models.PositiveIntegerField(),
        ),
    ]
