# Generated by Django 2.2.4 on 2021-04-14 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_auto_20210414_0301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='friends',
        ),
    ]
