# Generated by Django 2.2.4 on 2021-03-30 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_auto_20210331_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cena',
            field=models.PositiveIntegerField(),
        ),
    ]
