# Generated by Django 2.2.4 on 2021-04-14 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_friend'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
