# Generated by Django 2.2.4 on 2021-04-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_delete_friend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cena',
            field=models.PositiveIntegerField(default='0'),
        ),
    ]
