# Generated by Django 2.2.19 on 2021-05-26 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0063_auto_20210505_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='auth',
            name='zweryfikowany',
            field=models.BooleanField(default=False),
        ),
    ]
