# Generated by Django 2.2.19 on 2021-05-26 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_auth_zweryfikowany'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auth',
            name='zweryfikowany',
        ),
    ]
